name: restaurante
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  google_sign_in: ^5.4.2
  rxdart: ^0.27.7
  sqflite: any
  flutter_bloc: ^8.1.1
  permission_handler: ^10.2.0
  sizer: ^2.0.15
  equatable: ^2.0.5
  file_icon: ^1.0.0
  flutter_credit_card: ^3.0.4
  bottom_navy_bar: ^6.0.0  
  custom_navigation_bar: ^0.8.2
  font_awesome_flutter: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:  
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

