// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuNW2bb7f2aBdDJsDoIrq7KGsAIhpnpY4',
    appId: '1:978728716998:web:00240ba1efdb6b5350a5c7',
    messagingSenderId: '978728716998',
    projectId: 'restaurant-e28a1',
    authDomain: 'restaurant-e28a1.firebaseapp.com',
    storageBucket: 'restaurant-e28a1.appspot.com',
    measurementId: 'G-V365LECF5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBssInVMsLEcejilYPPn8eHuPWwB2VK2js',
    appId: '1:978728716998:android:ba469c64516ee5aa50a5c7',
    messagingSenderId: '978728716998',
    projectId: 'restaurant-e28a1',
    storageBucket: 'restaurant-e28a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_8pxDsFsEQp0C96O-YF-MzitIrOwNlw',
    appId: '1:978728716998:ios:b8e7caa26cc2486450a5c7',
    messagingSenderId: '978728716998',
    projectId: 'restaurant-e28a1',
    storageBucket: 'restaurant-e28a1.appspot.com',
    iosClientId: '978728716998-hkk3qg96c8vv04kue8q8i4m6r0s5nv89.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU_8pxDsFsEQp0C96O-YF-MzitIrOwNlw',
    appId: '1:978728716998:ios:b8e7caa26cc2486450a5c7',
    messagingSenderId: '978728716998',
    projectId: 'restaurant-e28a1',
    storageBucket: 'restaurant-e28a1.appspot.com',
    iosClientId: '978728716998-hkk3qg96c8vv04kue8q8i4m6r0s5nv89.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurante',
  );
}
